guanaco_development:
    infrastructure:
        authors:
            - name: Alexandre Andre
              email: alexandre@creakiwi.com
        composer:
            license: MIT
            requirements:
                require: ~
                require-dev: ~
